### PR TITLE
Wip

### PR DESCRIPTION
**Pull request by ericaashe**

### CODE REVIEW

**Comment by xofbd** [comment]
@ericaashe You need to merge this PR against _your_ forked copy of the repo `ericaashe/binder-framework`, not on TDI's.

**Comment by ericaashe** [comment]
Thank you. I was thinking it was something like that. I just couldn’t
figure out how to do it after everything was out of sync.

**Comment by ericaashe** [comment]
Hey Don,
My work is now missing from my local directory. I also don't know how my
branch was even connected to TDI's. I forked it and set up my
repository from my fork, not TDI's.

Anyway, do you know how to get my work back? It isn't on my github or in my
local folder now. But it was last night.

Thanks.

**Comment by xofbd** [comment]
@ericaashe 
I am guessing that when you opened up a Pull Request (PR), it may have defaulted as a PR against our copy and not yours (the one that was created when you forked).

>Anyway, do you know how to get my work back? It isn't on my github or in my
local folder now. But it was last night.

What does `git status` show? I think the work you are looking for is on the `WIP` branch. So `git checkout WIP` should bring that work to your working directory. I see that your repo on GitHub does have your work on this [branch](https://github.com/ericaashe/binder-framework/tree/WIP). 

If that's the work you are referring to, you'll need to merge into master. You can do so on GitHub by opening a PR asking to merge that branch, WIP, against master of your copy/fork.

**Comment by ericaashe** [comment]
I don't even have the work in my local folder (or anywhere on my computer
-- I was working from jupyter locally), regardless of branch. Do you think
I can roll back everything to get it back somehow?

**Comment by ericaashe** [comment]
My log only shows the original commits by you.

I can redo the work. It's fine. Thanks.

**Comment by xofbd** [comment]
It doesn't matter if it was on your computer or on JupyterHub server. While
you can redo the work, this is a good opportunity to better understand how
Git works (you may find yourself in a similar situation were redoing the
work is not a great option).
Does `git checkout WIP` followed by `git log` show the history of your work?

**Comment by ericaashe** [comment]
No. But I do now understand the process and even how to remove a single
commit with the commit's ID. My mistake has lead to learning, so not all is
lost.

And reprogramming isn't the worst thing for me right now as I'm trying to
learn.

Thanks for your help.

**Pull request closed without merging**
